version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_DATABASE=
      - MARIADB_ROOT_USER=
      - MARIADB_ROOT_PASSWORD=
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports: 
      - '3306:3306'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=
      - MOODLE_DATABASE_USER=
      - MOODLE_DATABASE_PASSWORD=
      - MOODLE_USERNAME=
      - MOODLE_PASSWORD=
      - MOODLE_EMAIL=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SMTP_PROTOCOL=

    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
